name: Reusable PHP CI

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to install'
        required: false
        type: string
        default: '8.3'
      working-dir:
        description: 'Sub‑folder in which to run composer / tests'
        required: false
        type: string
        default: '.'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs['php-version'] }}
          tools: composer

      - name: Install dependencies
        run: |
          cd ${{ inputs['working-dir'] }}
          if [ -f composer.json ]; then
            composer install --no-interaction --prefer-dist
          fi

      - name: Run PHPUnit
        if: ${{ inputs['working-dir'] != '' && hashFiles(format('{0}/phpunit.xml*', inputs['working-dir'])) != '' }}
        run: |
          cd ${{ inputs['working-dir'] }}
          vendor/bin/phpunit
