name: React CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint (optional)
        run: |
          if [ -f .eslintrc.js ]; then npm run lint; else echo "No lint config"; fi

      - name: Run Tests (optional)
        run: |
          if grep -q "test" package.json; then npm test -- --watchAll=false; else echo "No test config"; fi

      - name: Build React App
        run: npm run build

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app_name }}-build
          path: build/

      - name: Trigger CD Repo
        run: |
          gh workflow run react.yml -R nirajan-devops/ci-workflows \
            -f app_name=${{ inputs.app_name }} \
            -f artifact_name=${{ inputs.app_name }}-build
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
