name: React CI

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Application name"
        required: true
        type: string
      artifact_name:
        description: "Artifact name"
        required: true
        type: string

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: build/
