name: WordPress CI

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to test against'
        type: string
        default: '8.2'
      wordpress-version:
        description: 'WordPress version to test against'
        type: string
        default: 'latest'
      test-command:
        description: 'Custom test command to run'
        type: string
        default: 'composer test:ci'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion mysql-client wget

      - name: Install WP-CLI
        run: |
          wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          wp --info

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, dom, mysqli, intl, xml, curl
          coverage: none
          ini-values: memory_limit=512M

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Set up WordPress test library
        run: |
          # Create directory structure
          mkdir -p /tmp/wordpress-tests-lib/includes
          mkdir -p /tmp/wordpress-tests-lib/data
          
          # Download test files
          wget https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/bootstrap.php -P /tmp/wordpress-tests-lib/includes/
          wget https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/functions.php -P /tmp/wordpress-tests-lib/includes/
          wget https://develop.svn.wordpress.org/trunk/tests/phpunit/wp-tests-config-sample.php -P /tmp/wordpress-tests-lib/
          
          # Set up test config
          cp /tmp/wordpress-tests-lib/wp-tests-config-sample.php /tmp/wordpress-tests-lib/wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_test/g" /tmp/wordpress-tests-lib/wp-tests-config.php
          sed -i "s/yourusernamehere/wordpress/g" /tmp/wordpress-tests-lib/wp-tests-config.php
          sed -i "s/yourpasswordhere/wordpress/g" /tmp/wordpress-tests-lib/wp-tests-config.php
          sed -i "s/localhost/127.0.0.1/g" /tmp/wordpress-tests-lib/wp-tests-config.php

      - name: Prepare WordPress test environment
        run: |
          # Download WordPress core
          mkdir -p /tmp/wordpress
          wp core download --path=/tmp/wordpress --version=${{ inputs.wordpress-version }} --force
          
          # Copy wp-content from repository
          cp -r wp-content /tmp/wordpress/wp-content
          
          # Create wp-config.php
          wp config create \
            --path=/tmp/wordpress \
            --dbname=wordpress_test \
            --dbuser=wordpress \
            --dbpass=wordpress \
            --dbhost=127.0.0.1 \
            --force

          # Set test constants
          echo "<?php
          define('WP_DEBUG', true);
          define('WP_ENVIRONMENT_TYPE', 'ci');
          define('WP_TESTS_DIR', '/tmp/wordpress-tests-lib');
          ?>" >> /tmp/wordpress/wp-config.php

      - name: Run tests
        run: |
          export WP_TESTS_DIR=/tmp/wordpress-tests-lib
          export WP_ROOT_DIR=/tmp/wordpress
          ${{ inputs.test-command }}
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_ROOT_DIR: /tmp/wordpress

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/test-results.xml
          retention-days: 5