name: WordPress CI

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to test against'
        type: string
        default: '8.2'
      wordpress-version:
        description: 'WordPress version to test against'
        type: string
        default: 'latest'
      test-command:
        description: 'Custom test command to run'
        type: string
        default: 'composer test'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, dom, mysqli, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Set up WordPress test environment
        run: |
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/wordpress_test/g" wp-config.php
          sed -i "s/username_here/wordpress/g" wp-config.php
          sed -i "s/password_here/wordpress/g" wp-config.php
          sed -i "s/localhost/127.0.0.1/g" wp-config.php

      - name: Run tests
        run: ${{ inputs.test-command }}