name: WordPress CI

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to test against'
        type: string
        default: '8.2'
      wordpress-version:
        description: 'WordPress version to test against'
        type: string
        default: 'latest'
      test-command:
        description: 'Custom test command to run'
        type: string
        default: 'composer test'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, dom, mysqli, intl
          coverage: none

      - name: Install WordPress core
        run: |
          composer create-project johnpbloch/wordpress-core-installer:^2.0 wordpress-tmp --no-interaction
          mv wordpress-tmp/* .
          rm -rf wordpress-tmp

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Create wp-config.php
        run: |
          cat << 'EOF' > wp-config.php
          <?php
          define('DB_NAME', 'wordpress_test');
          define('DB_USER', 'wordpress');
          define('DB_PASSWORD', 'wordpress');
          define('DB_HOST', '127.0.0.1');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');
    
          define('AUTH_KEY',         'put your unique phrase here');
          define('SECURE_AUTH_KEY',  'put your unique phrase here');
          define('LOGGED_IN_KEY',    'put your unique phrase here');
          define('NONCE_KEY',        'put your unique phrase here');
          define('AUTH_SALT',        'put your unique phrase here');
          define('SECURE_AUTH_SALT', 'put your unique phrase here');
          define('LOGGED_IN_SALT',   'put your unique phrase here');
          define('NONCE_SALT',       'put your unique phrase here');
    
          \$table_prefix = 'wp_';
          define('WP_DEBUG', true);
          define('WP_ENVIRONMENT_TYPE', 'ci');
    
          if (!defined('ABSPATH')) {
            define('ABSPATH', __DIR__ . '/');
          }
    
          require_once ABSPATH . 'wp-settings.php';
          EOF

      - name: Run tests
        run: ${{ inputs.test-command }}